version: '3.8'

services:
  tsn_back:
    image: tsn_back:latest
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - /tmp
    environment:
      - SPRING_PROFILES_ACTIVE=dev # You can change this to the desired profile, e.g., prod, test, etc.
      - POSTGRES_PASSWORD=postgres
    entrypoint: ["java", "-jar", "/forix_back.jar", "--spring.profiles.active=${PROFILE}"]

volumes:
  tmp:

networks:
  forix:
    driver: bridge